### ISSUE TITLE
What is supposed to provide Hash#to_json ?

### ISSUE THREAD

**Issue by slyphon** [assaf/rack-oauth2-server#4]
I'm trying to write a bare-bones oauth2 server, using just sinatra and rack, and I hit [this line](https://github.com/assaf/rack-oauth2-server/blob/master/lib/rack/oauth2/server.rb#L393) and blew up.

What is supposed to provide Hash#to_json?

```
NoMethodError: undefined method `to_json' for #<Hash:0x007fe25c175048>
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-oauth2-server-2.4.1/lib/rack/oauth2/server.rb:393:in `rescue in respond_with_access_token'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-oauth2-server-2.4.1/lib/rack/oauth2/server.rb:352:in `respond_with_access_token'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-oauth2-server-2.4.1/lib/rack/oauth2/server.rb:190:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-protection-1.2.0/lib/rack/protection/path_traversal.rb:16:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-protection-1.2.0/lib/rack/protection/json_csrf.rb:17:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-protection-1.2.0/lib/rack/protection/base.rb:47:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-protection-1.2.0/lib/rack/protection/xss_header.rb:22:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/nulllogger.rb:9:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/head.rb:9:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/sinatra-1.3.2/lib/sinatra/showexceptions.rb:21:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `block in call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/sinatra-1.3.2/lib/sinatra/base.rb:1416:in `synchronize'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/sinatra-1.3.2/lib/sinatra/base.rb:1334:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/lint.rb:48:in `_call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/lint.rb:36:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/showexceptions.rb:24:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/commonlogger.rb:20:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/chunked.rb:43:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/content_length.rb:14:in `call'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/thin-1.3.1/lib/thin/connection.rb:80:in `block in pre_process'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/thin-1.3.1/lib/thin/connection.rb:78:in `catch'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/thin-1.3.1/lib/thin/connection.rb:78:in `pre_process'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/thin-1.3.1/lib/thin/connection.rb:53:in `process'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/thin-1.3.1/lib/thin/connection.rb:38:in `receive_data'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run_machine'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/eventmachine-0.12.10/lib/eventmachine.rb:256:in `run'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/thin-1.3.1/lib/thin/backends/base.rb:61:in `start'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/thin-1.3.1/lib/thin/server.rb:159:in `start'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/handler/thin.rb:13:in `run'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/server.rb:265:in `start'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/lib/rack/server.rb:137:in `start'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/gems/rack-1.4.0/bin/rackup:4:in `<top (required)>'
    /Users/slyphon/.rvm/gems/ruby-1.9.3-p0@oauth2_server/bin/rackup:19:in `load'
```

**Comment by gaku** [comment]
I've encountered the same issue with missing .to_json() method.

I have a Sinatra-based project with rack-oauth2-server built-in.  It crashed at respond_with_access_token of server.rb (https://github.com/assaf/rack-oauth2-server/blob/master/lib/rack/oauth2/server.rb#L442).

json gem was not imported by anybody.  The Sinatra test passes because test/setup.rb has require 'json' as well as 'rack/oauth2/server/admin.rb' also require 'json'.
